# Generated by Django 2.0.9 on 2018-11-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('legislative', '0005_auto_20171005_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Organization')),
                ('slug', models.SlugField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.event',),
        ),
    ]
