# Generated by Django 2.0.9 on 2018-11-30 04:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislative', '0005_auto_20171005_2028'),
        ('core', '0004_auto_20171005_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.bill',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.event',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.person',),
        ),
    ]
