# Generated by Django 2.0.9 on 2018-12-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('legislative', '0007_auto_20181029_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='councilmatic_bill', serialize=False, to='legislative.Bill')),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
            bases=('legislative.bill',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='councilmatic_event', serialize=False, to='legislative.Event')),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
            bases=('legislative.event',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='councilmatic_organization', serialize=False, to='core.Organization')),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='councilmatic_person', serialize=False, to='core.Person')),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='BillAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.billaction',),
        ),
        migrations.CreateModel(
            name='BillActionRelatedEntity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.billactionrelatedentity',),
        ),
        migrations.CreateModel(
            name='BillSponsorship',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.billsponsorship',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.membership',),
        ),
    ]
