# Generated by Django 2.1.3 on 2018-12-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0004_auto_20181203_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
