# Generated by Django 2.0.9 on 2018-12-05 03:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('councilmatic_core', '0005_auto_20181203_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.post',),
        ),
        migrations.AddField(
            model_name='person',
            name='headshot',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/fgregg/experiment/chi-councilmatic/static'), upload_to='your_image_name'),
        ),
    ]
