# Generated by Django 2.0.9 on 2018-12-06 15:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0006_auto_20181204_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='headshot',
            field=models.FileField(default='images/headshot_placeholder.png', storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/fgregg/experiment/chi-councilmatic/static'), upload_to='images'),
        ),
    ]
