# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0010_auto_20160120_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='division_ocd_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
