# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0019_auto_20161013_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='classification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
