# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0021_auto_20161014_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdocument',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
