# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0025_auto_20161017_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventagendaitem',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
