# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0029_auto_20170331_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventagendaitem',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
