# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-07 16:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0040_mediaevent_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.RunSQL('''
            INSERT INTO councilmatic_core_event (extras)
              WITH guids AS (
                SELECT guid
                FROM councilmatic_core_event
                WHERE guid IS NOT NULL
              )
              SELECT to_jsonb(guids) FROM guids
        ''', reverse_sql='''
            INSERT INTO councilmatic_core_event (guid)
              SELECT extras->'guid'
              FROM councilmatic_core_event
              WHERE extras->'guid' IS NOT NULL
        '''),
        migrations.RemoveField(
            model_name='event',
            name='guid',
        ),
    ]
