# Generated by Django 2.0.9 on 2018-12-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0005_auto_20171005_2028'),
        ('core', '0004_auto_20171005_2028'),
        ('councilmatic_core', '0043_membership_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='_bill',
        ),
        migrations.RemoveField(
            model_name='action',
            name='_organization',
        ),
        migrations.RemoveField(
            model_name='actionrelatedentity',
            name='_action',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='_from_organization',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='_legislative_session',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='eventagendaitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='eventagendaitem',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventdocument',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='_organization',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='_person',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='_post',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='_parent',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_organization',
        ),
        migrations.RemoveField(
            model_name='relatedbill',
            name='central_bill',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='_bill',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='_person',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='bill',
        ),
        migrations.CreateModel(
            name='BillAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.billaction',),
        ),
        migrations.CreateModel(
            name='BillSponsorship',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.billsponsorship',),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionRelatedEntity',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillDocument',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventAgendaItem',
        ),
        migrations.DeleteModel(
            name='EventDocument',
        ),
        migrations.DeleteModel(
            name='EventMedia',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
        migrations.DeleteModel(
            name='Jurisdiction',
        ),
        migrations.DeleteModel(
            name='LegislativeSession',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='RelatedBill',
        ),
        migrations.DeleteModel(
            name='Sponsorship',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.bill',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.event',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.membership',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.post',),
        ),
        migrations.CreateModel(
            name='PostShape',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='councilmatic_core.Post')),
                ('shape', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
