# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-11 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0044_bill_restrict_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='source_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
