# Generated by Django 2.1.8 on 2019-05-23 19:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('councilmatic_core', '0045_auto_20190513_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization',
        ),
        migrations.AlterField(
            model_name='person',
            name='headshot',
            field=models.FileField(default='images/headshot_placeholder.png', storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/Hannah/hackz/datamade/chi-councilmatic/static'), upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.organization',),
        ),
    ]
