# Generated by Django 2.1.9 on 2019-07-16 19:41

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0008_longer_event_name'),
        ('councilmatic_core', '0048_post_shape'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillAction',
        ),
        migrations.DeleteModel(
            name='BillSponsorship',
        ),
        migrations.CreateModel(
            name='BillAction',
            fields=[
                ('billaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislative.BillAction')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('legislative.billaction',),
        ),
        migrations.CreateModel(
            name='BillSponsorship',
            fields=[
                ('billsponsorship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislative.BillSponsorship')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('legislative.billsponsorship',),
        ),
    ]
