language: python

python: '3.5'

env:
    - db_user=postgres

addons:
  postgresql: '9.4'

install:
    - pip install --upgrade -r tests/test_requirements.txt
    - pip install -e .

sudo: required 
dist: trusty 
group: deprecated-2017Q4

script:
    - flake8 ./councilmatic_core/*.py
    - pytest
