# Generated by Django 4.2.23 on 2025-07-17 13:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("section", 13)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [[("rich_text", 1)]],
                                {},
                            ),
                            4: ("councilmatic_cms.blocks.NavigationBlock", (), {}),
                            5: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 1, "help_text": "Mobile phone"},
                            ),
                            6: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 2, "help_text": "Tablet"},
                            ),
                            7: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 4, "help_text": "Desktop"},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("sm", 5), ("md", 6), ("lg", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.StreamBlock", [[("table", 3)]], {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("breakpoints", 8), ("content", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("text", 1),
                                        ("image", 2),
                                        ("table", 3),
                                        ("navigation", 4),
                                        ("responsive_element", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Add anchor to enable direct links to this section",
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("content", 11), ("anchor", 12)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
